# Rename this file to env.py

# TELEGRAM TOKEN
TOKEN = ''

# PERSONAL INFO
BOT_NAME = ''
COMMUNITY_SITE = ''
COMMUNITY_GH = ''
COMMUNITY_GH_ISSUES = ''
COMMUNITY_GH_API_ISSUES = ''
COMMUNITY_NAME = ''
